### ISSUE TITLE
Invalid IHDR data error

### ISSUE THREAD

**Issue by hardikchauhan8** [ashitani/YOLO_chainer#1]
Hello,

I am trying to run this demo in Ubuntu 16.04 and getting error,

>libpng warning: Image width is zero in IHDR
>libpng warning: Image height is zero in IHDR
>libpng error: Invalid IHDR data
>Result was written to  004545_marked.png

Can you help me with this?

**Comment by ashitani** [comment]
Try to change these lines in YOLOtiny_chainer/predict.py from:

```
      im_marked=cv2.rectangle(im_marked, (int(x-w/2), int( y-h/2)),( int(x+w/2), int(y+h/2)),[0,0,255],thickness=2)
      im_marked=cv2.rectangle(im_marked, (int(x-w/2), int( y-h/2)),( int(x-w/2+100), int(y-h/2+20)),[0,0,255],thickness=-1)
```
to:
```
      cv2.rectangle(im_marked, (int(x-w/2), int( y-h/2)),( int(x+w/2), int(y+h/2)),[0,0,255],thickness=2)
      cv2.rectangle(im_marked, (int(x-w/2), int( y-h/2)),( int(x-w/2+100), int(y-h/2+20)),[0,0,255],thickness=-1)
```
(remove" im_marked==" from both lines).

It's depend on OpenCV version, but anyway that's to be modified.

**Comment by hardikchauhan8** [comment]
Thanks @ashitani 

This solved my issue.

I have one more question, can this demo anyway work on an android mobile app for object detection?

**Comment by ashitani** [comment]
This demo can't be deployed on android devices directly.
Please look for other approaches. for example,
https://github.com/natanielruiz/android-yolo
Or, latest OpenCV also includes yolo algorithm. 

Anyway I close this issue. Thanks for the report.
